export const OCI_RECONCILIATION_REASONS = {
  NO_MATCHED_SESSION: 'NO_MATCHED_SESSION',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  NO_ADS_CLICK_ID: 'NO_ADS_CLICK_ID',
  TEST_CLICK_ID: 'TEST_CLICK_ID',
  CONSENT_MISSING: 'CONSENT_MISSING',
  /** @deprecated Prefer NO_EXPORTABLE_OCI_STAGE for panel OCI enqueue audit */
  NOT_EXPORTABLE_STAGE: 'NOT_EXPORTABLE_STAGE',
  NO_EXPORTABLE_OCI_STAGE: 'NO_EXPORTABLE_OCI_STAGE',
  MERGED_CALL: 'MERGED_CALL',
  OUTBOX_INSERT_FAILED: 'OUTBOX_INSERT_FAILED',
} as const;

export type OciReconciliationReason =
  (typeof OCI_RECONCILIATION_REASONS)[keyof typeof OCI_RECONCILIATION_REASONS];
