/**
 * Canonical Google Ads OCI sync engine marker.
 *
 * The deployable script is generated by
 * `npm run build:google-ads-script -- --site=<slug>`.
 *
 * The builder uses `scripts/google-ads-oci/GoogleAdsScriptUniversal.js` as the
 * executable engine template and injects per-site inline config from
 * `scripts/google-ads-oci/sites/<slug>.json`. Keeping all generated site scripts
 * tied to that one template prevents per-site logic drift while legacy
 * hand-maintained forks were **removed** from the repo (see `fleet-quarantine.json`,
 * `FLEET_QUARANTINE.md`, `tests/fixtures/google-ads-oci/`).
 */
