/**
 * Canonical Google Ads OCI sync engine marker.
 *
 * The deployable script is generated by
 * `npm run build:google-ads-script -- --site=<slug>`.
 *
 * The builder currently uses `scripts/google-ads-oci/GoogleAdsScriptProduction.js`
 * as the executable engine template and injects per-site inline config from
 * `scripts/google-ads-oci/sites/<slug>.json`. Keeping all generated site scripts
 * tied to that one production template prevents per-site logic drift while the
 * legacy hand-maintained scripts are phased out.
 */
