-- =============================================================================
-- OCI_TRUTH_PR-C / LEDGER_WARNING
-- Prefer approved repair paths (cron recover-processing, RPCs). Ad-hoc UPDATE on
-- offline_conversion_queue bypasses oci_queue_transitions — use only in frozen
-- forensic copies; see docs/runbooks/OCI_QUEUE_REPAIR_INDEX.md
-- =============================================================================
-- Eslamed: Stuck PROCESSING rows → RETRY (recover cron does this automatically every 10 min)
-- Use this for manual recovery when cron hasn't run yet.
-- Site: b1264552-c859-40cb-a3fb-0ba057afd070
--
-- FROZEN FORENSIC: status UPDATE disabled in-repo. Prefer recover-processing cron / RPCs.
-- Incident-only copy below (keep commented):
-- UPDATE offline_conversion_queue
-- SET status = 'RETRY', next_retry_at = NULL, claimed_at = NULL, updated_at = now()
-- WHERE site_id = 'b1264552-c859-40cb-a3fb-0ba057afd070'
--   AND status = 'PROCESSING';
